---
- name: Start example
  block:
    - name: Create example Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ example_data_directory }}"

    - name: example
      community.docker.docker_container:
        name: "{{ example_container_name }}"
        image: "{{ example_image_name }}:{{ example_image_version }}"
        pull: true
        volumes:
          - "{{ example_pron_directory }}:/data:rw"
          - "{{ example_download_directory }}:/downloads:rw"
          - "{{ example_data_directory }}:/config:rw"
        ports:
          - "{{ example_port }}:6969"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ example_user_id }}"
          PGID: "{{ example_group_id }}"
          UMASK: "002"
        restart_policy: unless-stopped
        memory: "{{ example_memory }}"
        labels:
          traefik.enable: "{{ example_available_externally | string }}"
          traefik.http.routers.example.rule: "Host(`{{ example_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.example.tls.certresolver: "letsencrypt"
          traefik.http.routers.example.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.example.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.example.loadbalancer.server.port: "6969"
          homepage.group: "Download Tools"
          homepage.name: "example"
          homepage.icon: "example"
          homepage.href: "http://{{ ansible_nas_hostname }}:{{ example_port }}"
          homepage.description: Pr0n DVR
          homepage.widget.type: example
          homepage.widget.url: "http://{{ ansible_nas_hostname }}:6969"
          homepage.widget.key: "{{ example_token }}"
          homepage.widget.enableQueue: "false"
  when: example_enabled is true

- name: Stop example
  block:
    - name: Stop example
      community.docker.docker_container:
        name: "{{ example_container_name }}"
        state: absent
  when: example_enabled is false
